version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.16
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: kin
          POSTGRES_PASSWORD: kin
          POSTGRES_DB: kin_test
    steps:
      - checkout
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get github.com/mattn/goveralls
      - run: echo "POSTGRES_URL=postgresql://localhost:5432/kin_test?user=kin&password=kin&sslmode=disable" > .env
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: go test -v -covermode=count -coverprofile=coverage.out
      - run: goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_TOKEN
