version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
        environment:
          KIN_POSTGRES_URL: postgresql://localhost:5432/kin_test?user=kin&sslmode=disable
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: kin
          POSTGRES_DB: kin_test
    working_directory: /go/src/github.com/jmataya/kin
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get github.com/mattn/goveralls
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: POSTGRES_URL=$KIN_POSTGRES_URL go test -v -covermode=count -coverprofile=coverage.out
      - run: goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_TOKEN
